name: Daily getter

on:
  schedule:
    - cron: '53 2,3,17 * * *'
  workflow_dispatch:

jobs:
  getter:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run getter
        run: python main.py

      - name: Force-push single commit to dedicated branch
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

          git checkout --orphan data
          git reset
          git add data.json
          git commit -m "chore: automated product data update"
          git push origin data --force
